spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  r2dbc:
    password: password
    url: r2dbc:postgresql://localhost/dev?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Jakarta&useSSL=false
    username: dev
debug: true
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: info
